ProjetoMongoDB/Controllers/EventoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MongoDB.Driver;
using ProjetoMongoDB.Models;
using ProjetoMongoDB.Services;
using ProjetoMongoDB.ViewModels;
using Rotativa.AspNetCore;

namespace ProjetoMongoDB.Controllers
{
    public class EventoController : Controller
    {
        private readonly ContextMongoDb _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public EventoController(ContextMongoDb context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Evento
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Evento.Find(_ => true).ToListAsync());
        }

        // GET: Evento/Details/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.Find(m => m.Id == id).FirstOrDefaultAsync();

            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // GET: Evento/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Evento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao,Data,Tipo,HorarioInicio,HorarioFim")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                evento.Id = Guid.NewGuid();
                await _context.Evento.InsertOneAsync(evento);
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Evento/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.Find(m => m.Id == id).FirstOrDefaultAsync();

            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Evento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nome,Descricao,Data,Tipo,HorarioInicio,HorarioFim")] Evento eventoAtualizado)
        {
            if (id != eventoAtualizado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // 1. CARREGAR O EVENTO ORIGINAL
                    var eventoOriginal = await _context.Evento
                        .Find(m => m.Id == eventoAtualizado.Id)
                        .FirstOrDefaultAsync();

                    if (eventoOriginal == null)
                    {
                        return NotFound();
                    }

                    // 2. ATUALIZAR OS DADOS DO EVENTO ORIGINAL (PRESERVANDO PARTICIPANTES)
                    eventoOriginal.Nome = eventoAtualizado.Nome;
                    eventoOriginal.Descricao = eventoAtualizado.Descricao;
                    eventoOriginal.Data = eventoAtualizado.Data; // GARANTINDO QUE A DATA ESTÁ AQUI
                    eventoOriginal.HorarioInicio = eventoAtualizado.HorarioInicio;
                    eventoOriginal.HorarioFim = eventoAtualizado.HorarioFim;
                    eventoOriginal.Tipo = eventoAtualizado.Tipo;

                    // 3. SUBSTITUIR O DOCUMENTO COMPLETO
                    await _context.Evento.ReplaceOneAsync(m => m.Id == eventoOriginal.Id, eventoOriginal);
                }
                catch (MongoException)
                {
                    if (!EventoExists(eventoAtualizado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventoAtualizado);
        }

        // GET: Evento/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.Find(m => m.Id == id).FirstOrDefaultAsync();

            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Evento/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _context.Evento.DeleteOneAsync(u => u.Id == id);

            return RedirectToAction(nameof(Index));
        }

        private bool EventoExists(Guid id) // por ser privado, apenas a própria classe pode executar ele
        {
            return _context.Evento.Find(e => e.Id == id).Any();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Participante")]
        public async Task<IActionResult> Registrar(Guid id)
        {
            // obter o usuário logado
            var user = await _userManager.GetUserAsync(User);

            // buscar o evento pelo id
            var evento = await _context.Evento.Find(e => e.Id == id).FirstOrDefaultAsync();

            if (evento == null)
            {
                return NotFound();
            }

            var filter = Builders<Evento>.Filter.Eq(e => e.Id, id);
            var update = Builders<Evento>.Update.AddToSet(e => e.Participantes, user.Id);
            var result = await _context.Evento.UpdateOneAsync(filter, update);

            if (result.IsAcknowledged)
            {
                if (result.ModifiedCount > 0)
                {
                    // disparar um evento que envia o e-mail para o inscrito
                    await EventoNotifier.DispararRegistro(user, evento);

                    TempData["Message"] = "Inscrição realizada com sucesso. Você receberá um e-mail com mais informações do evento";
                }
                else
                {
                    TempData["Message"] = "Você já está inscrito!";
                }
            }
            else
            {
                TempData["Error"] = "Tente novamente mais tarde! Sua inscrição não foi realizada";
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Participante")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancelar(Guid id)
        {
            // Busca o usuário logado
            var user = await _userManager.GetUserAsync(User);

            // Busca o Evento com o Id recebido para cancelamento
            var evento = await _context.Evento.Find(e => e.Id == id).FirstOrDefaultAsync();

            // Verifica se user ou evento retornou nulo, e caso sim, dará NotFound
            if (user == null || evento == null)
            {
                return NotFound();
            }

            // Verifica se o Id do usuário está na lista de Participantes do evento
            if (evento.Participantes.Contains(user.Id))
            {
                // Filtro MongoDB para encontrar o evento com o Id correspondente - Equal
                var filter = Builders<Evento>.Filter.Eq(e => e.Id, id);

                // Operação de atualização que remove o Id do usuário da lista de Participantes - Pull
                var update = Builders<Evento>.Update.Pull(e => e.Participantes, user.Id);

                // Executa a atualização, aplicando o Filter e o Update criados
                var result = await _context.Evento.UpdateOneAsync(filter, update);

                // Verifica se a atualização foi bem-sucedida e se alterou linhas, exibindo mensagens diferentes para caso sim ou caso não
                if (result.IsAcknowledged && result.ModifiedCount > 0)
                {
                    TempData["Message"] = "Sua inscrição foi cancelada com sucesso!";
                }
                else
                {
                    TempData["Error"] = "Não foi possível cancelar a sua inscrição.";
                }
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Participante")]
        public async Task<IActionResult> MeusCertificados()
        {
            var user = await _userManager.GetUserAsync(User);
            var agora = DateTime.Now;
            var dataAtual = DateOnly.FromDateTime(agora);

            var eventosPassados = await _context.Evento.Find(e => e.Participantes.Contains(user.Id) && (e.Data < dataAtual)).ToListAsync();

            return View(eventosPassados);
        }

        [Authorize(Roles = "Participante")]
        public async Task<IActionResult> Emitir(Guid id)
        {
            // Buscar os dados do usuário logado
            var user = await _userManager.GetUserAsync(User);

ProjetoMongoDB/Controllers/UserController.cs
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjetoMongoDB.Models;

namespace ProjetoMongoDB.Controllers
{
    public class UserController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private RoleManager<ApplicationRole> _roleManager;

        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET do CREATE
        public IActionResult Create(string role)   // IActionResult permite várias coisas, como views
        {
            ViewBag.Role = role;
            return View();
        }

        // POST do CREATE
        [HttpPost]
        public async Task<IActionResult> Create(User user, string role)
        {
            // Início do IF
            // Se estiver tudo ok com o modelo da classe, cria o usuário
            if (ModelState.IsValid)
            {
                // Atribuindo valores do objeto 'user' a uma nova instância de ApplicationUser, do Identity
                ApplicationUser appUser = new ApplicationUser();

                // Lógica para criar o UserName, a partir do nome. OBS: UserName não pode conter espaços ou
                // símbolos especiais
                string userName = user.NomeCompleto.Replace(" ", ""); // Remover o espaço
                var normalizedString = userName.Normalize(NormalizationForm.FormD); // Separa os acentos das letras
                StringBuilder sb = new StringBuilder();

                // Percorrendo as letras da variável para verificar se há caracteres especiais, acentos
                foreach (char letra in normalizedString) 
                { 
                    if (CharUnicodeInfo.GetUnicodeCategory(letra) != UnicodeCategory.NonSpacingMark)
                    {
                        // Se for válido, acrescenta no 'sb' a letra para construir o UserName
                        sb.Append(letra);
                    }
                };

                userName = sb.ToString().Normalize(NormalizationForm.FormC);

                // Retirando tudo que não for letras e números
                userName = Regex.Replace(userName, @"[^a-zA-Z0-9\s]", "");

                appUser.UserName = userName;
                appUser.Email = user.Email;
                appUser.NomeCompleto = user.NomeCompleto;

                IdentityResult result = await _userManager.CreateAsync(appUser, user.Password);

                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(appUser, role);
                    // ViewBag 'carrega' coisas pra view
                    ViewBag.Message = "Usuário cadastrado com sucesso"; 
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            // Fim do IF

            return View(user); // retorna os campos preenchidos para não ter a necessidade de reescrever, em caso de erro
        }

        // Inserir perfis no Banco de Dados - apenas Administradores
        [Authorize(Roles = "Administrador")]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> CreateRole(UserRole userRole)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _roleManager.CreateAsync(new ApplicationRole() { Name = userRole.RoleName });

                if (result.Succeeded)
                {
                    ViewBag.Message = "Tipo de usuário cadastrado com sucesso";
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View();
        }
    }
}

ProjetoMongoDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoMongoDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoMongoDB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoMongoDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        

                        <!-- Mostrar a partialView de administrador -->
                        <partial name="_LoginAdmin.cshtml" /> 

                        @if (User != null && User.Identity != null && User.Identity.IsAuthenticated)
                        // @if (User?.Identity?.IsAuthenticated ?? false) - É a mesma coisa
                        {
                            // Está logado. Opções: MeusEventos e sair
                            if (User.IsInRole("Participante"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-route-id="@User.Identity.Name" asp-controller="Home" asp-action="MeusEventos">Eventos Inscritos</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-route-id="@User.Identity.Name" asp-controller="Home" asp-action="Participacoes">Participações</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            // Não está logado. Opções: registrar ou entrar
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create" asp-route-role="Participante">Registrar</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Entrar</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProjetoMongoDB 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetoMongoDB/Views/Shared/_LoginAdmin.cshtml
@using Microsoft.AspNetCore.Authorization;

@if (User.Identity.IsAuthenticated)
{
	if (User.IsInRole("Administrador"))
	{
		<li class="nav-item">
			<a class="nav-link" asp-controller="Evento" asp-action="Create">Cadastrar Evento</a>
		</li>

		<li class="nav-item">
			<a class="nav-link" asp-controller="User" asp-action="CreateRole">Cadastrar Tipo</a>
		</li>
	};
}